#! /usr/bin/env python

import matplotlib.pyplot as plt
import numpy as np
import pickle
import numpy.ma as ma
import pyfits
from cursor import *
from rvm import *
from scipy import interpolate
from Chelli_Module import *
import scipy.interpolate as interp
from scipy.optimize import curve_fit
import os

def Voigt(x, A, mu, sigma,cont):
    #A, mu, sigma,cont = p
    return cont-A*np.exp(-(x-mu)**2/(2.*sigma**2))


#Leemos la referencia  de ThAr
file_Lune='th_calibered.fits'
file_Lune='/home/main/Documents/DRS/REDUCED/Narval_20161103_060020_th2.fits'
l=pyfits.open(file_Lune)
a=l[1].data
h0=l[0].header
h1=l[1].header
l.close()



Orderlimit=np.concatenate(([0],np.where(np.diff(a['wavelength_lane1'])<0)[0],[len(a['wavelength_lane1'])-1]))


#Leemos otro ThAr
file='/home/main/Documents/DRS/REDUCED/Narval_20161003_160900_th1.fits'
file='/home/main/Documents/DRS/REDUCED/Narval_20161003_160900_th2.fits'
l=pyfits.open(file)
aD=l[1].data
hD0=l[0].header
hD1=l[1].header
l.close()




plt.plot(a['wavelength_lane1'],a['intensity_lane1'])
plt.plot(aD['wavelength_lane1'],aD['intensity_lane1'])
plt.show()


#Ca IR: ordre 26=20+6
# O2 770nm: ordre 30=20+10



puntos=[]


### This file is generated by Line_selection.py

fin=open("ThAr_Line_Cal.pkl",'r')
Info=pickle.load(fin)
#{'Order':order,'Lines':puntos,'FWHM':fwhm,'EqWidth':eqwidth}                                  
fin.close()
order0=Info['Order']+1
lineas=np.asarray(Info['Lines'])


fich=[f for f in os.listdir('/home/main/Documents/DRS/REDUCED/') if f.endswith('th2.fits')]
print(fich)
Diff=np.zeros((40,len(fich)))	
for i,f in enumerate(fich[1:]):
	print(f)
	l=pyfits.open('/home/main/Documents/DRS/REDUCED/'+f)
	aD=l[1].data
	hD0=l[0].header
	hD1=l[1].header
	l.close()
	#plt.ion()
	for order in range(1,36):
		#plt.clf()
		#print('Order {0}'.format(20+order))
		w0=a['wavelength_lane1'][Orderlimit[order]]
		w1=a['wavelength_lane1'][Orderlimit[order-1]+1]
		dispersion=(w1-w0)/(Orderlimit[order-1]-Orderlimit[order]) #Angstroms/pixel
		Oprof=a['intensity_lane1'][Orderlimit[order-1]+1:Orderlimit[order]]
		Owv=a['wavelength_lane1'][Orderlimit[order-1]+1:Orderlimit[order]]
		OprofD=aD['intensity_lane1'][Orderlimit[order-1]+1:Orderlimit[order]]

		# contD=np.median(OprofD)
		# cont=np.median(Oprof)

		# OprofD=OprofD-contD
		# Oprof=Oprof-cont
		# OprofD=OprofD/np.amax(OprofD)
		# Oprof=Oprof/np.amax(Oprof)

		# v=Chelly(Oprof,OprofD,v0=0.1)
		# #print(v)
		# Diff[order,i]=v*3e10*dispersion/w1
		# puntos.append((w1+w0)/2.)

		cuales=ma.masked_inside(lineas,w0,w1)
		# plt.plot(Owv,Oprof)
		# plt.plot(Owv,OprofD)
		# plt.plot(Owv,shift_profile(OprofD,v),linestyle='--')
		# plt.show()
		c=[]
	
		for cual in lineas[cuales.mask]:
			plt.clf()
			aqui=np.argmin(abs(Owv-cual))
			ext=20
			if aqui>ext and aqui+ext<len(Owv):
				contA=np.amin(Oprof[aqui-ext:aqui+ext])
				contD=np.amin(OprofD[aqui-ext:aqui+ext])
				pA=Oprof[aqui-ext:aqui+ext]-contA
				pA=pA/pA.max()
				pD=OprofD[aqui-ext:aqui+ext]-contD
				pD=pD/pD.max()
				v=Chelly(pA,pD,v0=0.1)
				c.append(v)
				#puntos.append(cual)
				# plt.plot(Owv[aqui-ext:aqui+ext],pA)
				# plt.plot(Owv[aqui-ext:aqui+ext],pD)
				# plt.plot(Owv[aqui-ext:aqui+ext],shift_profile(pD,-v),'--g')
				# plt.title(v)
				# plt.show()
		Diff[order,i]=np.mean(c)#*3e10*dispersion/w1
	# 	#plt.subplot(1,2,1)
	# 		plt.plot(Owv[aqui-ext:aqui+ext],pA)
	# 		plt.plot(Owv[aqui-ext:aqui+ext],pD)
	# 		plt.plot(Owv[aqui-ext:aqui+ext],shift_profile(pD,v),'--g')
	# 		plt.title(v)
	# 		plt.show()
	#plt.subplot(1,2,2)	
	#for i in range(40):
	#	plt.plot(Diff[i,:],'.')
	plt.imshow(Diff,aspect='auto',interpolation='nearest')
	plt.colorbar()
	plt.show()


#	plt.show()
	
	
for i in range(40):
	plt.plot(Diff[i,:],'.')
plt.title('All done')
plt.show()	
	
	
	
	

	
	

