#! /usr/bin/env python

import matplotlib.pyplot as plt
import numpy as np
import pickle
import numpy.ma as ma
import pyfits
from cursor import *
from rvm import *
from scipy import interpolate
from Chelli_Module import *
import scipy.interpolate as interp
from scipy.optimize import curve_fit

def Voigt(x, A, mu, sigma,cont):
    #A, mu, sigma,cont = p
    return cont-A*np.exp(-(x-mu)**2/(2.*sigma**2))





# On lit l'atlas solaire sur a
atlas="/Users/arturo/DeepStokes/SolarSpectrum.pkl"
f=open(atlas,'r')
atlas=pickle.load(f)
f.close()

#Leemos la observacion de Narval
file_Lune='luna_normalised.fts'
l=pyfits.open(file_Lune)
a=l[1].data
h0=l[0].header
h1=l[1].header
l.close()

#Leemos la mascara
file_mask='G2_ekdra'
f=open(file_mask,'r')
cuantos=int(f.readline())
lineas=np.zeros(cuantos)
for i,line in enumerate(f.readlines()):
	lineas[i]=10.*float(line.split()[0])
f.close()

Orderlimit=np.concatenate(([0],np.where(np.diff(a['wavelength_lane1'])<0)[0],[len(a['wavelength_lane1'])-1]))


#Ca IR: ordre 26=20+6
# O2 770nm: ordre 30=20+10


error1=[]
error2=[]
errorD=[]
EWA=[]
EWN=[]
Res=[]
puntos=[]


### This file is generated by Line_selection.py

fin=open("Lambda_Cal.pkl",'r')
Info=pickle.load(fin)
#{'Order':order,'Lines':puntos,'Error':error2}                                  
fin.close()
order0=Info['Order']+1
lineas=np.asarray(Info['Lines'])
error2=Info['Error']
		


for order in range(1,36):
	
	print('Order {0}'.format(20+order))
	w0=a['wavelength_lane1'][Orderlimit[order]]
	w1=a['wavelength_lane1'][Orderlimit[order-1]+1]
	
	
	
	donde=ma.masked_inside(atlas["Wavelength"],w0,w1)
	watlas=np.asarray(atlas["Wavelength"])[donde.mask]
	Fatlas=np.asarray(atlas["Intensity"])[donde.mask]
	p=interpolate.InterpolatedUnivariateSpline(watlas,Fatlas)
	
	
	
	
	
	dispersion=(w1-w0)/(Orderlimit[order-1]-Orderlimit[order]) #Angstroms/pixel
	Oprof=a['intensity_lane1'][Orderlimit[order-1]+1:Orderlimit[order]]
	Owv=a['wavelength_lane1'][Orderlimit[order-1]+1:Orderlimit[order]]
	
	cuales=ma.masked_inside(lineas,w0,w1)
	
	for cual in lineas[cuales.mask]:
	
		aqui=np.argmin(abs(Owv-cual))
	
		#try:
		ext=7
		
		if ext<aqui<len(Oprof)-ext :
			cont=np.amax(Oprof[aqui-ext:aqui+ext])
			if cont>0:
				p0 = [1., 0., 1.,cont]
				coeff, var_matrix = curve_fit(Voigt,np.arange(-ext,ext),Oprof[aqui-ext:aqui+ext], p0=p0,bounds=([0.1,-3,0.1,0.],[1.,3,3.,1.5]))
				aquiA=np.argmin(abs(watlas-cual))
				dispersion=(Owv[aqui+10]-Owv[aqui-10])/20.
				p0 = [1., 0., 1.,1.]
				coeffA, var_matrix = curve_fit(Voigt,np.arange(-20,20),Fatlas[aquiA-20:aquiA+20], p0=p0)
				dispAtlas=(watlas[aquiA+50]-watlas[aquiA])/50.
				DeltaS=dispersion*coeff[2]-dispAtlas*coeffA[2]
				#print(dispersion*coeff[2],dispAtlas*coeffA[2])
				if abs(coeff[1])<ext and DeltaS>0 and abs(DeltaS)<2:
					#plt.plot(watlas,Fatlas)	
				
					escala=1.#1000.*3e5/i
					#error1.append((cual-(Owv[aqui]+dispersion*coeff[1]))*escala)
					error1.append((watlas[aquiA]+dispAtlas*coeffA[1]-(Owv[aqui]+dispersion*coeff[1]))*escala)
					errorD.append(DeltaS)
					EWN.append(coeff[0]*coeff[2]*dispersion*np.sqrt(2.*np.pi))
					EWA.append(coeffA[0]*coeffA[2]*dispAtlas*np.sqrt(2.*np.pi))
					#errorEW.append(EW-EWA)
					puntos.append(watlas[aquiA]+dispAtlas*coeffA[1])
					Res.append((dispersion*coeff[2])**2-(dispAtlas*coeffA[2])**2)
				else:
					print(coeff[1],DeltaS)
plt.subplot(2,1,1)
plt.plot(puntos,error1,'b.')
plt.title(r'Position error: {0:.3f} $\pm$ {1:.3f} $\AA$'.format(np.mean(error1),np.std(error1)))
plt.ylabel(r'Error ($\AA$)')
plt.subplot(2,1,2)
plt.plot(EWN,EWA,'r,')
plt.ylabel(r'Atlas Eq. Width ($\AA$)')
plt.xlabel(r'Narval Eq. Width ($\AA$)')
plt.plot(np.arange(0,.5,0.1),np.arange(0,.5,0.1),'b--')
plt.show()	
	# plt.cla()
# 	plt.plot(puntos,error1,'b.')
# 	plt.title(r'Position error: {0:.3f}$\pm$ {1:.3f} $\AA$'.format(dispersion*np.mean(error1),dispersion*np.std(error1)))
# 	plt.ylabel('Error (A)')
# 	
# 	
# 	plt.draw()
# 	
	
	

